import { z } from 'zod'
import { SessionModeSchema, SessionStatusSchema } from './shared.schema'

// ─── Message ──────────────────────────────────────────────────────────────────

export const NudgeSchema = z.object({
  message: z.string(),
  pinTopic: z.string(),  // topic to return to
})

export const MessageSchema = z.object({
  id: z.string(),
  role: z.enum(['mentor', 'user']),
  content: z.string(),
  timestamp: z.string().datetime(),
  nudge: NudgeSchema.optional(),         // present on mentor messages when drift detected
})

export type Message = z.infer<typeof MessageSchema>
export type Nudge = z.infer<typeof NudgeSchema>

// ─── Session ──────────────────────────────────────────────────────────────────
// Persisted after stream closes via SessionSaveHandler.
// title is auto-generated by Claude (Haiku) after session ends.

export const SessionSchema = z.object({
  sessionId: z.string(),
  userId: z.string(),
  title: z.string(),                         // auto-generated, e.g. "BFS/DFS revision"
  mode: SessionModeSchema,
  topic: z.string().optional(),              // primary topic detected for this session
  status: SessionStatusSchema,
  messages: z.array(MessageSchema),
  tags: z.array(z.string()).default([]),     // e.g. ["DSA", "graphs"]
  summary: z.string().optional(),            // narrative recap, written post-session
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  endedAt: z.string().datetime().optional(),
  durationMinutes: z.number().int().min(0).optional(),
})

export type Session = z.infer<typeof SessionSchema>

// Lightweight session list item — used in sidebar, no messages loaded
export const SessionListItemSchema = SessionSchema.pick({
  sessionId: true,
  title: true,
  mode: true,
  topic: true,
  status: true,
  tags: true,
  summary: true,
  createdAt: true,
  durationMinutes: true,
})

export type SessionListItem = z.infer<typeof SessionListItemSchema>

// ─── Evaluation Session ───────────────────────────────────────────────────────

export const VerdictSchema = z.enum(['strong', 'partial', 'weak'])
export type Verdict = z.infer<typeof VerdictSchema>

export const EvalQuestionSchema = z.object({
  questionId: z.string(),
  level: z.enum(['recall', 'application', 'depth']),
  question: z.string(),
  userAnswer: z.string().optional(),
  verdict: VerdictSchema.optional(),
  feedback: z.string().optional(),
})

export const EvalSessionSchema = z.object({
  sessionId: z.string(),
  userId: z.string(),
  topic: z.string(),
  questions: z.array(EvalQuestionSchema),
  score: z.object({
    correct: z.number().int().min(0),
    total: z.number().int().min(1),
  }).optional(),
  status: z.enum(['in_progress', 'complete']),
  createdAt: z.string().datetime(),
  completedAt: z.string().datetime().optional(),
})

export type EvalSession = z.infer<typeof EvalSessionSchema>
export type EvalQuestion = z.infer<typeof EvalQuestionSchema>
